export default async function handler(req, res) {
    if (req.method !== "POST") {
        return res.status(405).json({
              error: "Méthode non autorisée."
                  });
                    }

                      try {
                          const apiKey = process.env.AGNES_API_KEY;

                              if (!apiKey) {
                                    return res.status(500).json({
                                            error: "AGNES_API_KEY n'est pas configurée sur le serveur."
                                                  });
                                                      }

                                                          const {
                                                                prompt,
                                                                      image,
                                                                            negativePrompt,
                                                                                  width = 1152,
                                                                                        height = 768,
                                                                                              numFrames = 121,
                                                                                                    frameRate = 24,
                                                                                                          seed
                                                                                                              } = req.body || {};

                                                                                                                  if (!prompt || !prompt.trim()) {
                                                                                                                        return res.status(400).json({
                                                                                                                                error: "Le prompt vidéo est obligatoire."
                                                                                                                                      });
                                                                                                                                          }

                                                                                                                                              if (numFrames > 441 || (numFrames - 1) % 8 !== 0) {
                                                                                                                                                    return res.status(400).json({
                                                                                                                                                            error: "numFrames doit être inférieur ou égal à 441 et respecter la formule 8n+1."
                                                                                                                                                                  });
                                                                                                                                                                      }

                                                                                                                                                                          if (frameRate < 1 || frameRate > 60) {
                                                                                                                                                                                return res.status(400).json({
                                                                                                                                                                                        error: "frameRate doit être compris entre 1 et 60."
                                                                                                                                                                                              });
                                                                                                                                                                                                  }

                                                                                                                                                                                                      const payload = {
                                                                                                                                                                                                            model: "agnes-video-v2.0",
                                                                                                                                                                                                                  prompt: prompt.trim(),
                                                                                                                                                                                                                        width,
                                                                                                                                                                                                                              height,
                                                                                                                                                                                                                                    num_frames: numFrames,
                                                                                                                                                                                                                                          frame_rate: frameRate
                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                  // Image de référence pour image-to-video
                                                                                                                                                                                                                                                      if (image) {
                                                                                                                                                                                                                                                            payload.image = image;
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                    // Prompt négatif facultatif
                                                                                                                                                                                                                                                                        if (negativePrompt) {
                                                                                                                                                                                                                                                                              payload.negative_prompt = negativePrompt;
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                      // Seed facultatif pour reproduire un résultat
                                                                                                                                                                                                                                                                                          if (seed !== undefined && seed !== null) {
                                                                                                                                                                                                                                                                                                payload.seed = seed;
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                        const response = await fetch(
                                                                                                                                                                                                                                                                                                              "https://apihub.agnes-ai.com/v1/videos",
                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                            method: "POST",
                                                                                                                                                                                                                                                                                                                                    headers: {
                                                                                                                                                                                                                                                                                                                                              "Authorization": `Bearer ${apiKey}`,
                                                                                                                                                                                                                                                                                                                                                        "Content-Type": "application/json"
                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                        body: JSON.stringify(payload)
                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                                                      const data = await response.json();

                                                                                                                                                                                                                                                                                                                                                                                          if (!response.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                return res.status(response.status).json({
                                                                                                                                                                                                                                                                                                                                                                                                        success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                error: "Agnes a refusé la génération vidéo.",
                                                                                                                                                                                                                                                                                                                                                                                                                        details: data
                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                      return res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  provider: "agnes",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        model: "agnes-video-v2.0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              video_id: data.video_id || null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    task_id: data.task_id || data.id || null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          status: data.status || "queued",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                progress: data.progress ?? 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      error: "Erreur lors de la communication avec Agnes.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            details: error.message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
}
